server:
    port: 8888

spring:
    data:
        redis:
            host: ${EAGLE_FILM_REDIS_HOST}
            port: ${EAGLE_FILM_REDIS_PORT}

discord:
    url: ${EAGLE_FILM_DISCORD_WEBHOOK}

mongodb:
    connectionString: ${EAGLE_FILM_MONGODB_CONNECTION_STRING}

cloud:
    aws:
        s3:
            endpoint: https://kr.object.ncloudstorage.com
        credentials:
            access-key: ${EAGLE_FILM_S3_ACCESS_KEY}
            secret-key: ${EAGLE_FILM_S3_SECRET_KEY}
            bucket: ${EAGLE_FILM_S3_BUCKET}
        region:
            static: ap-southeast-2
            auto: false
        stack:
            auto: false

logging:
    level:
        root: info
        com:
            mongodb: info
        org:
            apache:
                http: info


noti:
    url: ${EAGLE_FILM_NOTI_URL}

cors:
    allowed: "*"
