server:
    port: 8080
    ssl:
        key-store: ${EAGLE_FILM_SSL_KEY_STORE}
        key-store-type: ${EAGLE_FILM_SSL_KEY_STORE_TYPE}
        key-store-password: ${EAGLE_FILM_SSL_KEY_STORE_PASSWORD}
    tomcat:
        basedir: .
        accesslog:
            enabled: true
            pattern: %{yyyy-MM-dd HH:mm:ss}t\\t%s\\t%r\\t%{User-Agent}i\\t%{Referer}i\\t%a\\t%b

spring:
    rabbitmq:
        host: dev.eagle-film.vsfe.me
        port: 5672
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 100MB
    data:
        redis:
            host: ${EAGLE_FILM_REDIS_HOST}
            port: ${EAGLE_FILM_REDIS_PORT}

mongodb:
    connectionString: ${EAGLE_FILM_MONGODB_CONNECTION_STRING}

oauth:
    kakao:
        clientCode: e60282fe069d1c422ec1078ee4a29929
        redirectUri: https://eaglefilm.photo/kakao-token

cloud:
    aws:
        s3:
            endpoint: https://kr.object.ncloudstorage.com
            rl: ${EAGLE_FILM_S3_RESOURCE_LOCATION}
        credentials:
            access-key: ${EAGLE_FILM_S3_ACCESS_KEY}
            secret-key: ${EAGLE_FILM_S3_SECRET_KEY}
            bucket: ${EAGLE_FILM_S3_BUCKET}
        region:
            static: ap-southeast-2
            auto: false
        stack:
            auto: false

file:
    dir: /

logging:
    level:
        root: debug
        com:
            mongodb: info
        org:
            apache:
                http: info

noti:
    url: ${EAGLE_FILM_NOTI_URL}

cors:
    allowed: ${EAGLE_FILM_CORS_ALLOW}
