spring:
    rabbitmq:
        host: dev.eagle-film.vsfe.me
        port: 5672
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 100MB


mongodb:
    connectionString: mongodb://dev.eagle-film.vsfe.me:27017/eagle-film

oauth:
    kakao:
        clientCode: 16eacb1188b754a5da7af414528a9d08
        redirectUri: http://dev.eagle-film.vsfe.me:8080/api/v1/user/login/kakao

cloud:
    aws:
        s3:
            endpoint: https://kr.object.ncloudstorage.com
        credentials:
            access-key: Zu0qI1feJYNCQ5Vicjmu
            secret-key: df80kKN99LqMPkwK04o6BbPnxe35tkKLLchl6Ou0
            bucket: eagle-film-dev
        region:
            static: ap-southeast-2
            auto: false
        stack:
            auto: false

file:
    dir: /

logging:
    level:
        root: debug
