server:
    port: 9999
discord:
    token: ${EAGLE_FILM_DISCORD_TOKEN}
    channel: ${EAGLE_FILM_DISCORD_CHANNEL}
    alarmChannel: ${EAGLE_FILM_DISCORD_ALARM}
consumer:
    address: ${EAGLE_FILM_CONSUMER_ADDRESS}
bg:
    token: ${EAGLE_FILM_BG_TOKEN}
    url: ${EAGLE_FILM_BG_URL}
